#!/bin/bash

cache_dir="$HOME/.cache/.jumpo"
cache="$cache_dir/aliases"
tmp_cache="$cache_dir/tmp"

if [ ! -d "$cache_dir" ]; then
	mkdir "$cache_dir"
fi
touch "$cache"
touch "$tmp_cache"

function config_template() {
	echo "Alias |    Path    | Editor"
}

function rm_line() {
	eval "sed -i '$1d' $cache"
}

function alias_not_found() {
	echo "error: Alias not found."
}

function alias_already_exists() {
	echo "error: Alias already exists."
}

function usage() {
	echo "Usage: "
	echo ""
	echo "   jumpo add <editor> [path] [alias]"
	echo "                      default path is current working directory." 
	echo "			    default alias in directory name."
	echo "   jumpo rm <alias>"
	echo "   jumpo edit <alias>"
	echo "   jumpo show [alias]"
	echo "   jumpo [--help]"
}

function alias_exists() {
	name="$1"
	[ -n "$(awk -v alias="$name" '$1 == alias {print $0}' "$cache")" ]
}

if [ "$1" = "add" ]; then
	if [ $# -gt 2 ]; then
		real_path=$(realpath "$3")
		if [ $# -gt 3 ]; then
			if ! alias_exists "$4"; then
				echo "$4   $real_path   $2" >> "$cache"
			else
				alias_already_exists
			fi
		else
			alias_name=$(echo "$real_path" | awk -F "/" '{print $NF}')
			if ! alias_exists "$alias_name"; then
				echo "$alias_name   $real_path   $2" >> "$cache"
			else
				alias_already_exists
			fi
		fi
	else
		usage
	fi
elif [ "$1" = "rm" ]; then
	rm_alias="$2"
	if [ -n "$rm_alias" ]; then
		if alias_exists "$rm_alias"; then 
			rm_line_num=$(awk  -v alias="$rm_alias"	'{
								if($1 == alias)
									print NR
							}' "$cache")
			rm_line "$rm_line_num"
		else
			alias_not_found
		fi			
	else
		usage	
	fi
elif [ "$1" = "edit" ]; then
	if [ $# -gt 1 ]; then
		if alias_exists "$2"; then
			edit_alias="$2"
			read -p "Enter new alias name: " _new_alias
			read -p "Enter new project path: " _new_path
			read -p "Enter new editor name: " _new_editor
			edit_line_num=$(awk  -v alias="$edit_alias"	'{
								if($1 == alias)
									print NR
							}' "$cache")
			[ -n "$_new_alias" ] && 
			new_file=$(awk -v line="$edit_line_num" -v new="$_new_alias" '{ if(NR == line) { sub($1, new); } print $0 }' "$cache") &&
			echo "$new_file" > "$cache"
			[ -n "$_new_path" ] && 
			new_file=$(awk -v line="$edit_line_num" -v new="$_new_path" '{ if(NR == line) { sub($2, new); } print $0 }' "$cache") &&
			echo "$new_file" > "$cache"
			[ -n "$_new_editor" ] && 
			new_file=$(awk -v line="$edit_line_num" -v new="$_new_editor" '{ if(NR == line) { sub($3, new); } print $0 }' "$cache") &&
			echo "$new_file" > "$cache"
			echo "Changes were saved."
		else 
			alias_not_found
		fi
	else
		usage
	fi
elif [ "$1" = "show" ]; then
	if [ $# -gt 1 ]; then
		if alias_exists "$2"; then
			config_template 
			awk -v alias="$name" '$1 == alias {print $0}' "$cache"
		fi
	else
		if [ -s "$cache" ]; then
			config_template
			cat "$cache"
		fi
	fi
elif [ $# -lt 1 ] || [ "$1" == "--help" ]; then
	usage
else
	name=$1
	if alias_exists "$name"; then
		path="$(awk -v alias="$name" '$1 == alias {print $2}' "$cache")"
		editor="$(awk -v alias="$name" '$1 == alias {print $3}' "$cache")"
		echo "$path"
		echo "$(awk -v alias="$name" '$1 == alias {print $0}' "$cache")"
		cd "$path"
		$editor .
	else
		alias_not_found
	fi
fi
